{% set name = "platformio" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0251dd03d31c7ec89d30e5da582b7cad0f4332d9ec20648b672f26c623f885fc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - platformio = platformio.__main__:main
    - pio = platformio.__main__:main
    - piodebuggdb = platformio.__main__:debug_gdb_main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - bottle
    # PlatformIO specifies max versions of software that does not exist yet
    # I just removed the max version pinnings
    - click >=5,!=7.1.0,!=7.1.1
    - colorama
    - pyserial >=3,!=3.3
    - requests >=2.4.0
    - semantic_version >=2.8.1
    - tabulate >=0.8.3
    - pyelftools >=0.25
    - marshmallow >=2

test:
  imports:
    - platformio

about:
  home: https://platformio.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PlatformIO is a new generation ecosystem for embedded development.
  dev_url: https://github.com/platformio/platformio-core

extra:
  recipe-maintainers:
    - hmaarrfk
